version: '3.5'

volumes:
  nginx-shared:

services:
  nginx:
    image: nginx:1.19-alpine
    hostname: nginx
    ports:
      - "80:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    restart: always
    depends_on:
      - web

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    restart: always

  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - /data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env_staging
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh
    restart: always
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_PASSWORD

  worker: &worker
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env_staging
    depends_on:
      - db
      - redis
    command: docker/web/celery/worker/run.sh
    restart: always
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_PASSWORD

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh
    restart: always

